// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pedagio-mobile/PedagioMobile.tsx": () => import("../components/mockups/pedagio-mobile/PedagioMobile.tsx"),
  "./components/mockups/apresentacao/Capa.tsx": () => import("../components/mockups/apresentacao/Capa.tsx"),
  "./components/mockups/apresentacao/Contato.tsx": () => import("../components/mockups/apresentacao/Contato.tsx"),
  "./components/mockups/apresentacao/Diferenciais.tsx": () => import("../components/mockups/apresentacao/Diferenciais.tsx"),
  "./components/mockups/apresentacao/Servicos.tsx": () => import("../components/mockups/apresentacao/Servicos.tsx"),
  "./components/mockups/apresentacao/Sobre.tsx": () => import("../components/mockups/apresentacao/Sobre.tsx"),
  "./components/mockups/apresentacao/Tecnologia.tsx": () => import("../components/mockups/apresentacao/Tecnologia.tsx"),
  "./components/mockups/ignition-icons/Options.tsx": () => import("../components/mockups/ignition-icons/Options.tsx")
};
